/home/zzz/spirl-master/spirl/modules/layers.py:12: UserWarning: nn.init.xavier_normal is now deprecated in favor of nn.init.xavier_normal_.
  nn.init.xavier_normal(m.weight.data)
self.spec.env_name:  tensegrity_env-v0
Traceback (most recent call last):
  File "spirl/train.py", line 405, in <module>
    ModelTrainer(args=get_args())
  File "spirl/train.py", line 58, in __init__
    self.logger, self.model, self.train_loader = self.build_phase(train_params, 'train')
  File "spirl/train.py", line 307, in build_phase
    loader = self.get_dataset(self.args, model, self.conf.data, phase, params.n_repeat, params.dataset_size)
  File "spirl/train.py", line 316, in get_dataset
    loader = dataset_class(self._hp.data_dir, data_conf, resolution=model.resolution,
  File "/home/zzz/spirl-master/spirl/data/tense/kitchen_data_loader.py", line 27, in __init__
    self.dataset = excel_parse("./data/atomic_trajectory_0.csv")
  File "/home/zzz/spirl-master/spirl/excel.py", line 47, in excel_parse
    data = pd.read_csv(file_path)
  File "/home/zzz/miniconda3/envs/mujoco/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/zzz/miniconda3/envs/mujoco/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 678, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/zzz/miniconda3/envs/mujoco/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 581, in _read
    return parser.read(nrows)
  File "/home/zzz/miniconda3/envs/mujoco/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1253, in read
    index, columns, col_dict = self._engine.read(nrows)
  File "/home/zzz/miniconda3/envs/mujoco/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 225, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 805, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 861, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1960, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 5 fields in line 2378, saw 10
